//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEstacionamento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamentoDBEntities : DbContext
    {
        public EstacionamentoDBEntities()
            : base("name=EstacionamentoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CARRO> TB_CARRO { get; set; }
        public virtual DbSet<TB_ESTACIONAMENTO> TB_ESTACIONAMENTO { get; set; }
    }
}
