//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEstacionamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTACIONAMENTO
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string dataentrada { get; set; }
        public string datasaida { get; set; }
        public string nomecliente { get; set; }
        public string telefone { get; set; }
        public string valor { get; set; }
    }
}
